export const LOADING='LOADING'
export const GET_ALL_RECEIPS_SUCCESS='GET_ALL_RECEIPS_SUCCESS'
export const GET_ALL_RECEIPS_FAILED='GET_ALL_RECEIPS_FAILED'


//one receip
export const GET_ONE_RECEIPS_SUCCESS='GET_ONE_RECEIPS_SUCCESS'
export const GET_ONE_RECEIPS_FAILED='GET_ONE_RECEIPS_FAILED'
//search
export const GETSEARCHEDVALUE='GETSEARCHEDVALUE'